GerenciadorTelas:

    TelaPrincipal:
        name: "principal"
    ConsultarPessoa:
        name: "lista_pessoa"
    TelaPessoa:
        name: "pessoa"
    ConsultarUsuario:
        name: "consultar_usuario"
    TelaUsuario:
        name: "usuario"
    TelaItens:
        name: "principal_itens"
    ConsultarDoacao:
        name: "consultar_doacao"
    TelaDoacao:
        name: 'tela_doacao'

    LoginTela:
        name: "login"
