<ConfirmationPopup>:
    title: 'Confirmação'
    size_hint: 0.6, 0.4

    BoxLayout:
        orientation: 'vertical'

        Label:
            text: 'Deseja mesmo excluir este registro?'


        BoxLayout:
            orientation: 'horizontal'
            Button:
                text: 'Sim'
                on_release: root.confirm()

            Button:
                text: 'Não'
                on_release: root.dismiss()